web:
  build: .
  links:
   - db
  ports:
   - "8000:8000"
   - "9001:9001"
  volumes_from:
   - "baleen-config"
  # uncomment this if you want to do local development on baleen
  # while it runs inside a container.
  #volumes:
  #- /path/to/baleen/src:/usr/local/baleen
  env_file: .env
db:
  image: postgres:9.4
  env_file: .env
